:source-lang: clojure

Evaluate each `form` in order. Each result of the previous `form` becomes an
intermediate value that is inserted into the last position in the form to be
evaluated.


== Parameters
`x`: the starting value or form to evaluate      +
`forms`: additional forms to evaluate and insert intermediate values into


== Return value
The evaluated result of the last form


== Examples
[source]
----
(->> (range 1 11)   <1>
     (filter even?) <2>
     (reduce *))    <3>
;; => 3840
----
<1> start with integers 1 through 10
<2> keep only even integers
<3> multiply all the integers together

== Description
This is also known as the "thread-last" macro.

Roughly, it transforms this:
[source]
----
(->> 123
     (* 5)
     (- 10)
     (println))
----

into something like:

[source]
----
(let [result1 123
      result2 (* 5 result1)
      result3 (- 10 result2)
      result4 (println result3)
  result4)
----

This is very useful when constructing complex expression that transform data.
The threading macro makes the various stages of data transformation simple to
parse visually (compared to a complex s-expression). Stages can also be easily
added or removed without severely impacting the code structure.

The thread-last macro works very well with the `map`/`reduce` family of functions
which usually expects a collection as the last parameter.


== See Also
`clojure.core/->`
`clojure.core/as->`
`clojure.core/some->`
`clojure.core/some->>`


== Further Reading
https://clojure.org/guides/threading_macros
