:source-lang: clojure
Execute the `body` repeatedly with bindings defined by `seq-exprs`.


== Parameters
`seq-exprs`: binding pairs in the shape of `[name sequence]`
`body`: the expression to evaluate repeatedly


== Return value
nil


== Examples
=== Iterating through a sequence
[source,clojure]
----
(doseq [i (range 5)] <1>
  (println i)) <2>
;; 1
;; 2
;; 3
;; 4
;; 5
----
<1> create a binding named 'i' which will take on the value of the sequence `(range 5)` with each iteration
<2> execute expression with the new value of the binding

=== Combinatorial binding behavior
[source,clojure]
----
(doseq [x (range 1 3)
        y (range 4 6)]
  (println x y))
;; x y
;; ---
;; 1 4
;; 1 5
;; 2 4
;; 2 5
----


== Description

Clojure typically encourages the functional and immutable programming style.
`doseq`, however, is specifically meant for executing side effects over some
collection(s).

Since the function always returns nil, there is no way to capture or record what
exactly happened when those side effects were executed.

The function is very similar to `clojure.core/for`, except it only executes the
`body`, instead of collecting the results of `body` into a sequence.

FIXME! Add docs for :let, :while, and :when modifiers

== Exceptions


== See Also
`clojure.core/for`
